
// color naming conventions from (some of the newer/weirder ones):
// https://digitalsynopsis.com/design/color-thesaurus-correct-names-of-shades/

export const lightBlue = '#23A5DD'
export const blue = '#007AFF'
export const blueDark = '#2269A3'
export const blueDarker = '#0F3E65'
export const blueFaded = '#9DCDE0'
export const red = '#E30521'
export const orange = '#FF9500'
export const orangeFire = '#F59522'
export const orangeGold = '#E67E00'
export const green = '#3AB03E'
export const greenDark = '#3FA692'
export const greenDarker = '#15715F'
export const greenFaded = '#C0E2C4'
export const white = '#FFFFFF'
export const lightestGray = '#F2F2F2'
export const lightestGray2 = '#F8F8F8'
export const customGray = '#EFEFF4'
export const lightGray = '#E5E5EA'
export const lightGray2 = '#DFDFDF'
export const midGray = '#C7C7CC'
export const gray = '#8E8E93'
export const darkGray = '#6D6D72'
export const grayDarker = '#343434'
export const black = '#030303'
export const transparent = 'transparent'
